<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MyOs.Core\MyOs.Core.csproj" />
    <ProjectReference Include="..\MyOs.Ipc\MyOs.Ipc.csproj" />
    <ProjectReference Include="..\MyOs.Services\MyOs.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
